services:
  testando_nestjs_app:
    build: .
    container_name: testando_nestjs_app
    ports:
      - '3000:3000'
    networks:
      - internal_network
    depends_on:
      - db
    environment:
      - NODE_ENV=docker
      - DB_HOST=db
      - DB_USER=dockerdb
      - DB_PASSWORD=dockerdb
      - DB_NAME=teste_nestjs
    deploy:
      resources:
        limits:
          cpus: '1' # 100% de um core para lidar com alta carga
          memory: '2G' # Limite de 2 GB de RAM para a aplicação
        reservations:
          cpus: '0.5' # Reserva 50% de um core
          memory: '1G' # Reserva 1 GB de RAM para a aplicação

  db:
    image: 'postgres:latest'
    container_name: testando_nestjs_db
    environment:
      - 'POSTGRES_DB=teste_nestjs'
      - 'POSTGRES_USER=dockerdb'
      - 'POSTGRES_PASSWORD=dockerdb'
    ports:
      - '5432:5432'
    networks:
      - internal_network
    deploy:
      resources:
        limits:
          cpus: '1' # 100% de um core para o banco
          memory: '2G' # Limite de 2 GB de RAM para o banco
        reservations:
          cpus: '0.5' # Reserva 50% de um core para o banco
          memory: '1G' # Reserva 1 GB de RAM para o banco

networks:
  internal_network:
    driver: bridge